### ISSUE TITLE
S3Objects macro fails PutObject with "the bucket does not allow ACLs"

### ISSUE THREAD

**Issue by zaro0508** [aws-cloudformation/aws-cloudformation-macros#22]
The S3Objects macro fails to deploy files to a bucket that has ACLs disabled.

steps to repro:
1. Create a bucket
2. [Disable ACLs on the bucket](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-ownership-existing-bucket.html) by setting it to `BucketOwnerEnforced`.
3.  Use the [S3Objects macro](https://github.com/aws-cloudformation/aws-cloudformation-macros/tree/master/S3Objects) to put a file into the bucket.

```
NewObject:
  Type: AWS::S3::Object
  Properties:
    Target:
      Bucket: !Ref TargetBucket
      Key: README.md
    Body: |
      # My text file
```

4.  Get the following error on deployment..

```
[ERROR] ClientError: An error occurred (AccessControlListNotSupported) when calling the
PutObject operation: The bucket does not allow ACLs
Traceback (most recent call last):
  File "/var/task/resource.py", line 72, in handler
    s3_client.put_object(**target)
  File "/var/runtime/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
[ERROR] ClientError: An error occurred (AccessControlListNotSupported) when calling the
PutObject operation: The bucket does not allow ACLs Traceback (most recent call last):
File "/var/task/resource.py", line 72, in handler     s3_client.put_object(**target)   
File "/var/runtime/botocore/client.py", line 391, in _api_call     return self._make_api_call(operation_name, kwargs)   
File "/var/runtime/botocore/client.py", line 719, in _make_api_call     raise error_class(parsed_response, operation_name)
```

**Comment by zaro0508** [comment]
Actually I had the `ACL` setting in my template which caused the failure.  for example..

```
NewObject:
  Type: AWS::S3::Object
  Properties:
    Target:
      ACL: authenticated-read
```

The S3Object macro seems to work fine after removing that setting.
